account/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fdvworkflow.views.home', name='home'),
    # url(r'^fdvworkflow/', include('fdvworkflow.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^$','supermilai.views.index'),
    #url(r'^register.html','account.views.account_register'),
    url(r'^login.html','account.views.account_login'),
    url(r'^logout.html','account.views.account_logout'),
    url(r'^password_change.html$','account.views.account_password_change'),
    url(r'^profile/view.html','account.views.account_view_profile'),
    url(r'^profile/edit/id=(.+)$','account.backend_manage.user_modify'),

    url(r'^manage/user_list.html','account.backend_manage.user_list'),
    url(r'^manage/add_user.html$','account.backend_manage.user_add'),
    url(r'^manage/modify/user/id=(.+)$','account.backend_manage.user_modify'),
    url(r'^manage/remove/user/id=(.+)$','account.backend_manage.user_remove'),

    url(r'^manage/group_list.html','account.backend_manage.group_list'),
    url(r'^manage/add_group.html$','account.backend_manage.group_add'),
    url(r'^manage/modify/group/id=(.+)$','account.backend_manage.group_modify'),
    url(r'^manage/remove/group/id=(.+)$','account.backend_manage.group_remove'),

    url(r'^manage/permission_list.html','account.backend_manage.permission_list'),
    url(r'^manage/add_permission.html$','account.backend_manage.permission_add'),
    url(r'^manage/modify/permission/id=(.+)$','account.backend_manage.permission_modify'),
    #url(r'^manage/remove/user/id=(.+)$','account.backend_manage.user_remove'),

    url(r'^ajax/set_active_status.html','account.ajax.set_active_status'),
    url(r'^ajax/set_group.html','account.ajax.set_group'),
    #url(r'^account_manage.html$','account.views.account_manage'),
    #url(r'^account_manage/add_group.html$','account.views.add_group'),
    #url(r'^account_manage/modify_group/modify/id=(.+)$','account.views.modify_group'),
    #url(r'^account_manage/delete_group.html$','account.views.delete_group'),
)

supermilai/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'supermilai.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'supermilai.views.index', name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls')),
    url(r'^autotemplate/', include('autotemplate.urls')),
    url(r'^logistik/', include('logistik.urls')),
    url(r'^workflow/', include('workflow.urls')),
    url(r'^listcheck/', include('listcheck.urls')),
    url(r'^static/(?P<path>.*)', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),

    url(r'^django-version$', 'supermilai.views.django_version', name='index'),
)

logistik/models.py
from account.models import UserProfile
from django.db import models

class Container(models.Model):
	#basic info
	PackingListNo = models.CharField(unique=True,max_length=30)

	#Timestamps
	packinglist_time = models.DateField(null=True,blank=True)
	depature_time = models.DateField(null=True,blank=True)
	leaving_port_time = models.DateField(null=True,blank=True)
	arrival_time = models.DateField(null=True,blank=True)

	status = models.CharField(max_length=10,null=True,blank=True)
	#Packing_items = models.ForeignKey(Item,through='Item')

	def __unicode__(self):
		return self.PackingListNo

	class Meta:
		ordering = ['PackingListNo']
		db_table = 'Container'
		permissions = (
			("view_container", "Can view containers"),
			)

	def get_status(self):
		if self.packinglist_time != None:
			if self.depature_time != None:
				status = 'shipping'
				if self.leaving_port_time != None:
					status = 'roading'
					if self.arrival_time != None:
						status = 'storing'
					else:
						status == 'roading'
				else:
					status = 'shipping'
			else:
				status = 'packing'
		else:
			status = 'error'
		return status

class Item(models.Model):
	sku = models.CharField(max_length=30,unique=True)
	hasTemp= models.BooleanField(default=False)
	hasDescription= models.BooleanField(default=False)
	manager = models.ForeignKey('account.UserProfile',null=True,blank=True)
	container = models.ForeignKey(Container)
	#temp_maker = models.CharField(max_length=30,null=True,blank=True)
	#description_maker = models.CharField(max_length=30,null=True,blank=True)

	def __unicode__(self):
		return self.sku

	class Meta:
		ordering = ['sku']
		db_table = 'Item'
		permissions = (
			("view_item", "Can view items"),
			)

templates/base_proj.html
<!Doctype html>
<html xmlns=http://www.w3.org/1999/xhtml>
<head>
	<meta charset="UTF-8">
	<meta http-equiv=Content-Type content="text/html;charset=utf-8">
	<title>{% block page_title %}{% endblock %} | FDV管理系统</title>

	{% block global_styles %}
		<link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
		<link href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
		<link href="/static/css/fdv.css" rel="stylesheet">
		<link href="/static/plugins/bootstrap-select/dist/css/bootstrap-select.min.css" rel="stylesheet">
		<link href="http://cdn.bootcss.com/bootstrap-datepicker/1.3.0/css/datepicker3.min.css" rel="stylesheet">
	{% endblock %}

	{% block page_level_styles %}
	{% endblock %}
</head>
<body style="margin-bottom:15px;">
<div class="container-fluid">
	<div id="navi" class="row">
		<div class="col-md-12">
			<!--navi-->
			{% block navibar %}
				{%include 'navibar.html'%}
			{% endblock %}
			<!--navi-->
		</div>
	</div>
	<div id="content" class="row">
		<div class="col-md-12">
			<div class="row-fluid">
				<div class="col-md-2 sidebar-menu">
					<!--sidebar-->
					{% block sidebar %}
						{%include 'sidebar.html'%}
					{% endblock %}
					<!--sidebar-->
				</div>
				<div class="col-md-10">
					<div class="row-fluid">
						<div class="col-md-12">
							<!--breadcrumb-->
							<h1>{% block content_title %}首页{% endblock %}</h1>
							{% block breadcrumb %}
							<ul class="breadcrumb">
								<li></li>
								<!--<li>
									<a href="#">首页</a>
									<span class="divider"></span>
								</li>
								<li>
									<a href="#">类目</a>
									<span class="divider"></span>
								</li>
								<li class="active">主题</li>-->
							</ul>
							{% endblock %}
							<!--breadcrumb-->
						</div>
					</div>
					<div class="row-fluid">
						<div class="col-md-12">
							{% block main_content %}
							{% endblock %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="footer" class="row">
		<div class="col-md-12">
			<!--footer-->
			{% block footer %}
				{%include 'footer.html'%}
			{% endblock %}
			<!--footer-->
		</div>
	</div>
</div>
	{% block global_plugins %}
		<script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
		<script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
		<script src="http://cdn.bootcss.com/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js"></script>
		<script src="http://cdn.bootcss.com/bootstrap-datepicker/1.3.0/js/locales/bootstrap-datepicker.zh-CN.min.js"></script>
		<script src="http://cdn.bootcss.com/twitter-bootstrap/3.2.0/js/tooltip.min.js"></script>
		<script src="http://cdn.bootcss.com/twitter-bootstrap/3.2.0/js/popover.min.js"></script>
		<!--<script src="http://cdn.bootcss.com/angular.js/1.3.0-beta.13/angular.min.js"></script>-->
	{% endblock %}

	{% block page_level_plugins %}
	{% endblock %}

	{% block global_scripts %}
	{% endblock %}

	{% block page_level_scripts %}
	{% endblock %}
</body>
</html>

templates/footer.html
<div class="footer navbar-fixed-bottom" style="height: 20px;">
	<p style="width:100%;text-align:center;">
		<small>
			Copyright 2009-2014 <i class="fa fa-copyright"></i> by
			<a href="http://weibo.com/raphaelsoul/">@Mr.Yasassi_Hentai</a>
		</small>
	</p>
</div>

templates/home_page.html
{% extends "base_proj.html" %}

{% block page_title %}首页{% endblock %}

{% block content_title %}首页{% endblock %}

{% block page_level_styles %}
{% endblock %}

{% block main_content %}
<img src="/static/img/48540923dd54564ef9f7e77eb1de9c82d0584fe2.jpg" alt="">
{% endblock %}

{% block page_level_scripts %}
{% endblock %}

templates/jumping.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-cn">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>页面跳转中...</title>
	<script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
	<script language=javascript>setTimeout('window.location="{{ redirecturls }}"',2000)</script>
</head>
<body>
	<h1>页面将会在2秒后跳转，请勿操作，谢谢!</h1>
	<h3>服务器返回的操作结果是:</h3>
	<h2>{{ report }}</h2>
</body>
</html>

templates/navibar.html
<nav class="navbar navbar-default" role="navigation">
	<div class="navbar-header">
		<a class="navbar-brand" href="#">FDV System</a>
	</div>
	<div>
		<!--向右对齐-->
		<ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					{{request.user.truename}} <b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li>
						<a href="/account/profile/view.html">帐号资料</a>
					</li>
					<li>
						<a href="/account/password_change.html">修改密码</a>
					</li>
					<li class="divider"></li>
					<li>
						<a href="/account/logout.html">登出</a>
					</li>
				</ul>
			</li>
		</ul>
		<p class="navbar-text navbar-right"></p>
	</div>
	<div>
		<!--向右对齐-->
		<ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					Task <b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li>
						<a href="#">###</a>
					</li>
					<li>
						<a href="#">###</a>
					</li>
					<li class="divider"></li>
					<li>
						<a href="#">###</a>
					</li>
				</ul>
			</li>
		</ul>
		<p class="navbar-text navbar-right"></p>
	</div>
	<div>
		<!--向右对齐-->
		<ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					Notifications <b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li>
						<a href="#">###</a>
					</li>
					<li>
						<a href="#">###</a>
					</li>
					<li class="divider"></li>
					<li>
						<a href="#">###</a>
					</li>
				</ul>
			</li>
		</ul>
		<p class="navbar-text navbar-right"></p>
	</div>
</nav>

templates/sidebar.html
<ul class="nav-header menu-first collapsed">
	<a href="/"> <i class="glyphicon glyphicon-dashboard"></i>
		访问首页
	</a>
</ul>
{% if perms.account.read_sidebar_account %}
<ul class ="nav-header menu-first collapsed" href="#userMenu" data-toggle="collapse">
	<a href="javascript:void(0);"> <i class="glyphicon glyphicon-user"></i>
		用户管理
	</a>
</ul>
<ul id="userMenu" class="nav nav-list collapse menu-second">
	<li>
		<a href="/account/manage/user_list.html">
			<i class="glyphicon glyphicon-user"></i> 用户列表
		</a>
	</li>
	<li>
		<a href="/account/manage/group_list.html">
			<i class="glyphicon glyphicon-arrow-right"></i> 权组列表
		</a>
	</li>
	{% if request.user.is_superuser %}
	<li>
		<a href="/account/manage/permission_list.html">
			<i class="glyphicon glyphicon-th"></i> 权限列表
		</a>
	</li>
	{%endif%}
</ul>
{%endif%}
<ul class="nav-header menu-first collapsed"  href="#logistikMenu" data-toggle="collapse">
	<a href="javascript:void(0);">
		<!--<i class="glyphicon glyphicon-refresh"> fa-anchor</i>-->
		<i class="fa fa-anchor"> </i>
		 海运物流
	</a>
</ul>
<ul id="logistikMenu" class="nav nav-list collapse menu-second">
	<li>
		<a href="/logistik/index.html">
			<i class="fa fa-life-ring"> </i> 物流总览
		</a>
	</li>
	{% if perms.logistik.add_container %}
	<li>
		<a href="/logistik/add_container.html"><i class="fa fa-mail-forward"> </i> 添加箱单</a>
	</li>
	{% endif %}
</ul>
{% if perms.account.read_sidebar_mission %}
<ul class="nav-header menu-first collapsed"  href="#workflow" data-toggle="collapse">
	<a href="javascript:void(0);">
		<i class="glyphicon glyphicon-pencil"></i>
		撰写任务
	</a>
</ul>
<ul id="workflow" class="nav nav-list collapse menu-second">
	<li>
		<a href="/workflow/all_tasks/page=1">
			<i class="fa fa-pencil"> </i> 任务分配
		</a>
	</li>
	<li>
		<a href="/workflow/my_tasks.html"><i class="fa fa-home"> </i> 我的任务</a>
	</li>
	<li>
		<a href="/logistik/view_all_items/page=1"><i class="fa fa-folder-open"> </i> 全部任务</a>
	</li>
	<!--<li>
		<a href="#">完成确认</a>
	</li>-->
</ul>
{% endif %}
{% if perms.account.read_sidebar_listverify %}
<ul class="nav-header menu-first collapsed"  href="#listcheckMenu" data-toggle="collapse">
	<a href="javascript:void(0);">
		<i class="glyphicon glyphicon-book"></i>
		上架审核
	</a>
</ul>
<ul id="listcheckMenu" class="nav nav-list collapse menu-second">
	<li>
		<a href="/listcheck/add_plan.html">
			<i class="fa fa-graduation-cap"> </i> 新增计划
		</a>
	</li>
	<li>
		<a href="/listcheck/mylistplan/page=1"><i class="fa fa-refresh"> </i> 我的计划</a>
	</li>
	{% if perms.account.read_chiildsidebar_handle %}
	<li>
		<a href="/listcheck/handle/page=1"><i class="fa fa-shield"> </i> 审核计划</a>
	</li>
	{% endif %}
</ul>
{% endif %}
<ul class="nav-header menu-first collapsed">
	<a href="/autotemplate"> <i class="glyphicon glyphicon-check"></i>
		模板制作
	</a>
</ul>